# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js (14.x)
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install Packages
      run: npm ci

    - name: Installing dependencies
      run: npm i --ignore-scripts

    - name: Build Step
      env:
        CI: ""
      run: npm run build --if-present

    - name: Running Linter - ESLint
      run: npm run lint

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
